const DisplayConstants = {
  OPEN_DRAWER: "OPEN_DRAWER",
  CLOSE_DRAWER: "CLOSE_DRAWER",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  SHOW_NOTEBOOK_FORM: "SHOW_NOTEBOOK_FORM",
  HIDE_NOTEBOOK_FORM: "HIDE_NOTEBOOK_FORM"
};

module.exports = DisplayConstants;
