const DisplayConstants = {
  OPEN_NOTEBOOK_DRAWER: "OPEN_NOTEBOOK_DRAWER",
  CLOSE_NOTEBOOK_DRAWER: "CLOSE_NOTEBOOK_DRAWER",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  SHOW_NOTEBOOK_FORM: "SHOW_NOTEBOOK_FORM",
  HIDE_NOTEBOOK_FORM: "HIDE_NOTEBOOK_FORM",
  OPEN_TAG_DRAWER: "OPEN_TAG_DRAWER",
  CLOSE_TAG_DRAWER: "CLOSE_TAG_DRAWER",
  TOGGLE_NOTES_TAGS: "TOGGLE_NOTES_TAGS",
  CLOSE_NOTES_TAGS: "CLOSE_NOTES_TAGS"
};

module.exports = DisplayConstants;
