const NotebookConstants = {
  RECEIVE_NOTEBOOK: "RECEIVE_NOTEBOOK",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  TOGGLE_FORM: "TOGGLE_FORM",
  RECEIVE_NOTEBOOKS: "RECEIVE_NOTEBOOKS"
};

module.exports = NotebookConstants;
