const NotebookConstants = {
  RECEIVE_EXISTING_NOTEBOOK: "RECEIVE_EXISTING_NOTEBOOK",
  RECEIVE_NEW_NOTEBOOK: "RECEIVE_NEW_NOTEBOOK",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  TOGGLE_FORM: "TOGGLE_FORM",
  RECEIVE_NOTEBOOKS: "RECEIVE_NOTEBOOKS",
  REMOVE_NOTEBOOK: "REMOVE_NOTEBOOK"
};

module.exports = NotebookConstants;
