const NotebookConstants = {
  RECEIVE_UPDATED_NOTEBOOK: "RECEIVE_UPDATED_NOTEBOOK",
  RECEIVE_NEW_NOTEBOOK: "RECEIVE_NEW_NOTEBOOK",
  TOGGLE_DRAWER: "TOGGLE_DRAWER",
  TOGGLE_FORM: "TOGGLE_FORM",
  RECEIVE_NOTEBOOKS: "RECEIVE_NOTEBOOKS"
};

module.exports = NotebookConstants;
