const NoteConstants = {
  SET_CURRENT_NOTE: "SET_CURRENT_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  START_DRAG: "START_DRAG",
  END_DRAG: "END_DRAG",
  RECEIVE_TAGGED_NOTES: "RECEIVE_TAGGED_NOTES"
};

module.exports = NoteConstants;
